name: Event 1
date: 12/15/2015
description: This is the description, come to the event homie
flyer_img: flyer.jpg
height: auto
---
name: Event 2
date: 12/15/2015
description: This is the description, come to the event homie
flyer_img: flyer.jpg
height: auto
---
name: Event 3
date: 12/15/2015
description: This is the description, come to the event homie
flyer_img: flyer.jpg
height: auto
---
name: Event 4
date: 12/15/2015
description: This is the description, come to the event homie
flyer_img: flyer.jpg
height: auto

