name: Health & Disease Management Info Session
date: 12/15/2015
description: Learn about simple dietary & lifestyle changes to manage and prevent GOUT DIABETES, HEART DISEASE, and other health information to live your best life! Presented by CWRU Medical Students & Food Recovery Network
flyer_img: health-flyer.jpg
height: auto