name: Bon-Appetit
img: bon-appetit.jpg
height: 200
---
name: CWRU Police
img: cwru-police.png
height: 200
---
name: Einstein Bros. Bagels
img: einstein.png
height: 200
---
name: Panera
img: panera.png
height: 200
---
name: Christian Church
img: christian-church.png
height: 200
---
name: Hunger Network of Greater Cleveland
img: hunger-network-cle.png
height: 200
---
name: CWRU Greek Life
img: cwru-greek.png
height: auto